### ISSUE TITLE
Trashcan icon and Cog Icon

### ISSUE THREAD

**Issue by richardsison** [DWilliames/paddy2-beta#19] opened 2018-05-21 04:10 UTC
https://d.pr/i/8991Sg

I'm not sure if this is a bug, but why does the "trashcan" icon and "cog" icon alternate when the Padding is on or off?

The trashcan icon behaves as expected (deletes padding) though I'd prefer to just keep it there the whole time. The "cog" icon however doesn't seem to do anything?

**Comment by aparajita** [comment] 2018-05-21 05:35
This is kind of a duplicate of #14, where this issue is discussed. Maybe better to upvote [this](https://github.com/DWilliames/paddy2-beta/issues/14#issuecomment-388892719).

**Comment by DWilliames** [comment] 2018-05-22 12:01
Yeah, the cog doesn't do anything at the moment.
I'll add it back when I get around to adding the 'Advanced padding options'.

I have also changed the behaviour so that the trash-can appears all the time in the latest v0.3 build. 👍

**Closed by DWilliames** 2018-05-22 12:01 UTC
